import { Platform, StatusBar, StyleSheet } from "react-native";

export const COLORS = {
  primaryRed: "#d32f2f", // Red for buttons and highlights
  bgLight: "#f5f5f5", // Background color
  white: "#ffffff",
  textBlack: "#000000",
  textGrey: "#757575",
  borderLight: "#e0e0e0",
  cardBg: "#f9f9f9",
};
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F8F9FB",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    alignItems: "center",
  },
  expertBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 25,
    padding: 6,
    paddingRight: 15,
    borderWidth: 1,
    borderColor: "#E0E4E8",
    elevation: 2,
  },
  expertIconBg: {
    backgroundColor: "#232F3E",
    padding: 6,
    borderRadius: 20,
    marginRight: 10,
  },
  expertText: { fontSize: 13, fontWeight: "700", color: "#232F3E" },
  profileCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#232F3E",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  scrollContent: { paddingBottom: 20 },
  trendingCard: {
    backgroundColor: "#fff",
    margin: 20,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EEF0F2",
    elevation: 5,
  },
  trendingRow: { flexDirection: "row", alignItems: "center" },
  trendingLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#8892A3",
    letterSpacing: 1,
    marginBottom: 4,
  },
  imagePlaceholder: {
    width: 55,
    height: 55,
    borderRadius: 16,
    backgroundColor: "#F0F3F6",
    marginRight: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  cardTitle: { fontSize: 17, fontWeight: "bold", color: "#1A1D1F" },
  divider: { height: 1, backgroundColor: "#F0F3F6", marginVertical: 15 },
  offerText: { fontSize: 13, color: "#444", fontWeight: "500" },
  darkCircleBtn: {
    backgroundColor: "#232F3E",
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionHeading: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1A1D1F",
    marginLeft: 20,
    marginTop: 15,
    marginBottom: 15,
  },
  grid: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
  },
  gridItem: {
    backgroundColor: "#fff",
    width: (width - 60) / 4,
    borderRadius: 20,
    paddingVertical: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EEF0F2",
    elevation: 2,
  },
  iconContainer: {
    width: 50,
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  gridLabel: {
    color: "#1A1D1F",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 14,
  },
  healthCheckCard: {
    flexDirection: "row",
    backgroundColor: "#FFF5F5",
    marginHorizontal: 20,
    marginTop: 15,
    padding: 15,
    borderRadius: 20,
    alignItems: "center",
  },
  healthIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  healthText: { fontSize: 14, color: "#232F3E", fontWeight: "500" },
  startAnalysis: { color: "#D32F2F", fontWeight: "bold", marginTop: 5 },
  sectionMainHeading: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 35,
  },
  sectionSubHeading: {
    fontSize: 15,
    color: "#8892A3",
    textAlign: "center",
    marginTop: 5,
  },
  ornamentLine: {
    height: 1,
    width: 60,
    backgroundColor: "#E0E4E8",
    alignSelf: "center",
    marginVertical: 15,
  },
  marketScroll: { paddingLeft: 20, paddingBottom: 10 },
  marketCard: {
    backgroundColor: "#fff",
    width: 180,
    borderRadius: 20,
    padding: 15,
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#EEF0F2",
    elevation: 3,
  },
  marketTag: {
    fontSize: 10,
    fontWeight: "bold",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    marginBottom: 10,
  },
  marketLogo: {
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  marketName: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1A1D1F",
    height: 40,
  },
  marketPrice: { fontSize: 15, fontWeight: "bold", marginTop: 5 },
  marketSub: { fontSize: 11, color: "#8892A3", marginTop: 3 },
  smallArrow: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E0E4E8",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  viewAllSharesBtn: {
    backgroundColor: "#D32F2F",
    margin: 20,
    padding: 18,
    borderRadius: 100,
    alignItems: "center",
  },
  viewAllSharesText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  trustedText: { color: "#fff", fontSize: 10, marginTop: 4, opacity: 0.8 },
  basketContainer: {
    backgroundColor: "#fff",
    margin: 20,
    padding: 25,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#EEF0F2",
  },
  basketTitle: { fontSize: 24, fontWeight: "bold", textAlign: "center" },
  basketSubtitle: {
    fontSize: 14,
    color: "#8892A3",
    textAlign: "center",
    marginTop: 5,
  },
  maximisedText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 20,
    marginTop: 10,
  },
  basketItem: { flexDirection: "row", alignItems: "center", marginBottom: 25 },
  basketItemTitle: { fontSize: 16, fontWeight: "bold" },
  basketItemSub: { fontSize: 13, color: "#8892A3", marginTop: 2 },
  redButton: {
    backgroundColor: "#D32F2F",
    padding: 18,
    borderRadius: 100,
    alignItems: "center",
  },
  redButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  referCard: {
    flexDirection: "row",
    margin: 20,
    padding: 20,
    backgroundColor: "#EBF2FF",
    borderRadius: 20,
    alignItems: "center",
  },
  referIconBox: {
    width: 45,
    height: 45,
    borderRadius: 10,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  referTitle: { fontSize: 16, fontWeight: "bold" },
  referSub: { fontSize: 12, color: "#8892A3" },
  videoScroll: { paddingLeft: 20, paddingBottom: 20 },
  videoCard: { width: 250, marginRight: 15 },
  videoThumb: {
    height: 140,
    backgroundColor: "#232F3E",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  videoTitle: { fontSize: 14, fontWeight: "600", marginTop: 10 },
  sectionHeadingCenter: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 40,
  },
  sectionSubCenter: {
    fontSize: 14,
    color: "#8892A3",
    textAlign: "center",
    marginBottom: 20,
  },
  cardScroll: { paddingLeft: 20, paddingBottom: 10 },
  fdCard: {
    backgroundColor: "#fff",
    width: 220,
    borderRadius: 24,
    padding: 20,
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#EEF0F2",
    elevation: 3,
  },
  bankCircle: { width: 40, height: 40, borderRadius: 20, marginBottom: 15 },
  bankSquare: { width: 40, height: 40, borderRadius: 8, marginBottom: 15 },
  bankName: { fontSize: 16, fontWeight: "700", height: 45 },
  uptoText: { fontSize: 12, color: "#8892A3", marginTop: 15 },
  rateText: { fontSize: 24, fontWeight: "bold", marginTop: 5 },
  pa: { fontSize: 12, fontWeight: "normal" },
  circleArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E0E4E8",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    marginTop: 15,
  },
  helpContainer: { padding: 20 },
  helpTitle: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  helpContent: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  helpBody: { fontSize: 16, color: "#444", lineHeight: 22 },
  bookSlotBtn: {
    backgroundColor: "#fff",
    borderColor: "#000",
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 100,
    alignSelf: "flex-start",
    marginTop: 15,
  },
  bookSlotText: { fontWeight: "bold" },
  expertAvatar: { width: 100, height: 100, borderRadius: 20 },
  supportList: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEF0F2",
    overflow: "hidden",
  },
  supportItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F3F6",
  },
  supportLabel: { flex: 1, marginLeft: 15, fontSize: 15, fontWeight: "600" },
  blogListContainer: {
    backgroundColor: "#fff",
    margin: 20,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EEF0F2",
  },
  blogItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F3F6",
  },
  blogThumb: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: "#F0F3F6",
  },
  blogItemTitle: { fontSize: 14, fontWeight: "700", color: "#000" },
  blogItemDate: { fontSize: 12, color: "#8892A3", marginTop: 4 },
  outlineButton: {
    borderColor: "#000",
    borderWidth: 1,
    padding: 16,
    borderRadius: 100,
    alignItems: "center",
    marginTop: 20,
  },
  outlineButtonText: { fontWeight: "bold" },
  footer: {
    padding: 25,
    borderTopWidth: 1,
    borderTopColor: "#F0F3F6",
    alignItems: "center",
  },
  footerBrandRow: { alignItems: "center", marginBottom: 20 },
  footerBrand: { fontSize: 18, fontWeight: "bold", color: "#232F3E" },
  footerCopyright: { fontSize: 12, color: "#8892A3", marginTop: 5 },
  disclaimerRow: { flexDirection: "row", alignItems: "center" },
  disclaimerText: { fontSize: 14, fontWeight: "bold", marginRight: 8 },

  // NEW STYLES FOR THE FRESH SECTIONS
  searchContainer: { paddingHorizontal: 20, marginTop: 10, marginBottom: 10 },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  searchInput: { flex: 1, marginLeft: 10, color: "#232F3E", fontSize: 14 },
  filterBtn: {
    padding: 5,
    borderLeftWidth: 1,
    borderLeftColor: "#F0F3F6",
    marginLeft: 10,
  },
  sentimentCard: {
    backgroundColor: "#fff",
    margin: 20,
    padding: 20,
    borderRadius: 24,
    elevation: 4,
  },
  sentimentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  sentimentTitle: { fontSize: 16, fontWeight: "bold", color: "#232F3E" },
  liveBadge: {
    backgroundColor: "#FFEDED",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 5,
  },
  liveText: { color: "#FF5252", fontSize: 10, fontWeight: "bold" },
  gaugeContainer: { height: 40, width: "100%" },
  gaugeTrack: {
    height: 8,
    backgroundColor: "#F0F3F6",
    borderRadius: 4,
    width: "100%",
    overflow: "hidden",
    justifyContent: "center",
  },
  gaugePointer: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#2E7D32",
    borderBottomWidth: 2,
    borderColor: "#fff",
    alignSelf: "center",
    position: "absolute",
    left: "75%",
  },
  gaugeLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  gaugeText: { fontSize: 12, color: "#8892A3" },
  launchScroll: { paddingLeft: 20, paddingBottom: 10 },
  launchCard: { width: 200, padding: 20, borderRadius: 20, marginRight: 15 },
  launchTag: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#000",
    opacity: 0.6,
    marginBottom: 5,
  },
  launchTitle: { fontSize: 16, fontWeight: "bold", color: "#232F3E" },
  launchDesc: { fontSize: 12, color: "#232F3E", opacity: 0.8, marginTop: 5 },

  grid: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 15,
  },
  gridItem: {
    backgroundColor: "#ffffff",
    width: (width - 60) / 2, // Spreads them evenly across the row
    borderRadius: 20,
    paddingVertical: 25,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EEF0F2",
    elevation: 2,
    // Shadow for iOS/Mac environment
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  iconContainer: {
    width: 50,
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  gridLabel: {
    color: "#1A1D1F",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 18,
  },
});
